version: '3.5'

services:
  ambassador:
    image: quay.io/datawire/ambassador:1.7.0
    ports:
    # expose port 8080 via 8080 on the host machine
    - 8080:8080
    volumes:
    # mount a volume where we can inject configuration files
    - ./config:/ambassador/ambassador-config
    environment:
    # don't try to watch Kubernetes for configuration changes
    - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
    extra_hosts:
    - "rated:92.168.1.94"
    
  backend:
    image: jgaafromnorth/rest-diag-svc
    expose:
    - 8080
    
